### ISSUE TITLE
error  TypeError: normalizeConnectArgs is not a function

### ISSUE THREAD

**Issue by pmudahar** [heroku/socksv5#1]
@jdxcode 

I've just started getting this error when the script runs on Heroku. 

```
error  TypeError: normalizeConnectArgs is not a function
2018-01-15T17:01:19.139465+00:00 app[web.1]:     at Object.exports.connect.exports.createConnection (/app/node_modules/socksv5/lib/client.js:225:14)
2018-01-15T17:01:19.139466+00:00 app[web.1]:     at sendFile (/app/app.js:681:8)
2018-01-15T17:01:19.139468+00:00 app[web.1]:     at /app/app.js:496:3
2018-01-15T17:01:19.139469+00:00 app[web.1]:     at <anonymous>
2018-01-15T17:01:19.139471+00:00 app[web.1]:     at process._tickCallback (internal/process/next_tick.js:188:7)
```

Any thoughts?

Thanks in advance.
Paul

**Comment by jdx** [comment]
that's why this fork exists, use `@heroku/socksv5` instead of `socksv5`

**Comment by pmudahar** [comment]
i actually did that today and its still not working.  The error just started on Friday, it had been running fine until then.

**Comment by pmudahar** [comment]
Sorry, it works.  I didn't properly uninstall socksv5 first. 

Thanks @jdxcode
